/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.av_car_auto_center.view;

/**
 *
 * @author gusta
 */
public class MenuMain extends javax.swing.JFrame {

    /**
     * Creates new form MenuMain
     */
    public MenuMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BntVeiculo = new javax.swing.JButton();
        BntFechar = new javax.swing.JButton();
        BntServico = new javax.swing.JButton();
        BntPeca = new javax.swing.JButton();
        BntColaboradores = new javax.swing.JButton();
        BntFornecedor = new javax.swing.JButton();
        BntOrdemServico = new javax.swing.JButton();
        BntFuncoes = new javax.swing.JButton();
        BntHistorico = new javax.swing.JButton();
        BntPagamento = new javax.swing.JButton();
        BntClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AV CAR AUTO CENTER");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT_Image_12_de_jun._de_2026_16_08_46_-_Editado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        BntVeiculo.setBackground(new java.awt.Color(223, 223, 223));
        BntVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntVeiculo.setForeground(new java.awt.Color(0, 0, 0));
        BntVeiculo.setText("Veículo");
        BntVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntVeiculoActionPerformed(evt);
            }
        });

        BntFechar.setBackground(new java.awt.Color(223, 223, 223));
        BntFechar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntFechar.setForeground(new java.awt.Color(0, 0, 0));
        BntFechar.setText("Fechar");
        BntFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntFecharActionPerformed(evt);
            }
        });

        BntServico.setBackground(new java.awt.Color(223, 223, 223));
        BntServico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntServico.setForeground(new java.awt.Color(0, 0, 0));
        BntServico.setText("Serviços");
        BntServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntServicoActionPerformed(evt);
            }
        });

        BntPeca.setBackground(new java.awt.Color(223, 223, 223));
        BntPeca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntPeca.setForeground(new java.awt.Color(0, 0, 0));
        BntPeca.setText("Peças");
        BntPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntPecaActionPerformed(evt);
            }
        });

        BntColaboradores.setBackground(new java.awt.Color(223, 223, 223));
        BntColaboradores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntColaboradores.setForeground(new java.awt.Color(0, 0, 0));
        BntColaboradores.setText("Colaboradores");
        BntColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntColaboradoresActionPerformed(evt);
            }
        });

        BntFornecedor.setBackground(new java.awt.Color(223, 223, 223));
        BntFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        BntFornecedor.setText("Fornecedor");
        BntFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntFornecedorActionPerformed(evt);
            }
        });

        BntOrdemServico.setBackground(new java.awt.Color(223, 223, 223));
        BntOrdemServico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntOrdemServico.setForeground(new java.awt.Color(0, 0, 0));
        BntOrdemServico.setText("Ordem de Serviço");
        BntOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrdemServicoActionPerformed(evt);
            }
        });

        BntFuncoes.setBackground(new java.awt.Color(223, 223, 223));
        BntFuncoes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntFuncoes.setForeground(new java.awt.Color(0, 0, 0));
        BntFuncoes.setText("Funções");
        BntFuncoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntFuncoesActionPerformed(evt);
            }
        });

        BntHistorico.setBackground(new java.awt.Color(223, 223, 223));
        BntHistorico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntHistorico.setForeground(new java.awt.Color(0, 0, 0));
        BntHistorico.setText("Historico de Proprietario");
        BntHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntHistoricoActionPerformed(evt);
            }
        });

        BntPagamento.setBackground(new java.awt.Color(223, 223, 223));
        BntPagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntPagamento.setForeground(new java.awt.Color(0, 0, 0));
        BntPagamento.setText("Pagamentos");
        BntPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntPagamentoActionPerformed(evt);
            }
        });

        BntClientes.setBackground(new java.awt.Color(223, 223, 223));
        BntClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntClientes.setForeground(new java.awt.Color(0, 0, 0));
        BntClientes.setText("Clientes");
        BntClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BntFuncoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntColaboradores, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(BntServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BntVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntOrdemServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(BntHistorico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntServico)
                    .addComponent(BntOrdemServico))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntVeiculo)
                    .addComponent(BntColaboradores))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntFornecedor)
                    .addComponent(BntClientes))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntPagamento)
                    .addComponent(BntPeca))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntFechar)
                    .addComponent(BntFuncoes))
                .addGap(45, 45, 45)
                .addComponent(BntHistorico)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_BntFecharActionPerformed

    private void BntServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntServicoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuServicos().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntServicoActionPerformed

    private void BntOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrdemServicoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOrdemServico().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntOrdemServicoActionPerformed

    private void BntColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntColaboradoresActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuColaboradores().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntColaboradoresActionPerformed

    private void BntFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntFornecedorActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFornecedor().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntFornecedorActionPerformed

    private void BntPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntPecaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPecas().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntPecaActionPerformed

    private void BntVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntVeiculoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVeiculo().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntVeiculoActionPerformed

    private void BntClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntClientesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClientes().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntClientesActionPerformed

    private void BntPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntPagamentoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPagamentos().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntPagamentoActionPerformed

    private void BntFuncoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntFuncoesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncoes().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntFuncoesActionPerformed

    private void BntHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntHistoricoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHistoricoProprietario().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntClientes;
    private javax.swing.JButton BntColaboradores;
    private javax.swing.JButton BntFechar;
    private javax.swing.JButton BntFornecedor;
    private javax.swing.JButton BntFuncoes;
    private javax.swing.JButton BntHistorico;
    private javax.swing.JButton BntOrdemServico;
    private javax.swing.JButton BntPagamento;
    private javax.swing.JButton BntPeca;
    private javax.swing.JButton BntServico;
    private javax.swing.JButton BntVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
