/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.av_car_auto_center.view;

import com.av_car_auto_center.Controller.FuncaoController;
import com.av_car_auto_center.model.Funcao;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class MenuFuncoes extends javax.swing.JFrame {

    /**
     * Creates new form MenuFuncoes
     */
    public MenuFuncoes() {
        initComponents();
        
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("IDFunção");
        modelo.addColumn("Ativo");
        modelo.addColumn("Descrição");

        FuncaoController controller = new FuncaoController();
        List<Funcao> funcoes = controller.listarAtivos();

        for (Funcao f : funcoes) {
            modelo.addRow(new Object[]{
                f.getID(),
                f.isAtivo() ? "Sim" : "Não",
                f.getDescricao()
            });
        }

        TableFuncao.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFuncao = new javax.swing.JTable();
        BntMenu = new javax.swing.JButton();
        BntAdd = new javax.swing.JButton();
        BntDesativar = new javax.swing.JButton();
        BntBuscar = new javax.swing.JButton();
        BntAtivos = new javax.swing.JButton();
        BntInativos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BntAtivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Funções");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT_Image_12_de_jun._de_2026_16_08_46_-_Editado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        TableFuncao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IDFunção", "Ativo", "Descrição"
            }
        ));
        TableFuncao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableFuncaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableFuncao);

        BntMenu.setBackground(new java.awt.Color(223, 223, 223));
        BntMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntMenu.setForeground(new java.awt.Color(0, 0, 0));
        BntMenu.setText("Menu");
        BntMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenuActionPerformed(evt);
            }
        });

        BntAdd.setBackground(new java.awt.Color(223, 223, 223));
        BntAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntAdd.setForeground(new java.awt.Color(0, 0, 0));
        BntAdd.setText("Adicionar");
        BntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAddActionPerformed(evt);
            }
        });

        BntDesativar.setBackground(new java.awt.Color(223, 223, 223));
        BntDesativar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntDesativar.setForeground(new java.awt.Color(0, 0, 0));
        BntDesativar.setText("Desativar");
        BntDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntDesativarActionPerformed(evt);
            }
        });

        BntBuscar.setBackground(new java.awt.Color(223, 223, 223));
        BntBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntBuscar.setForeground(new java.awt.Color(0, 0, 0));
        BntBuscar.setText("Buscar");

        BntAtivos.setBackground(new java.awt.Color(223, 223, 223));
        BntAtivos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntAtivos.setForeground(new java.awt.Color(0, 0, 0));
        BntAtivos.setText("Ativos");

        BntInativos.setBackground(new java.awt.Color(223, 223, 223));
        BntInativos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntInativos.setForeground(new java.awt.Color(0, 0, 0));
        BntInativos.setText("Inativos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mostrar");

        BntAtivar.setBackground(new java.awt.Color(223, 223, 223));
        BntAtivar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntAtivar.setForeground(new java.awt.Color(0, 0, 0));
        BntAtivar.setText("Ativar");
        BntAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAtivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BntMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BntAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(BntDesativar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BntBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BntAtivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BntInativos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BntAtivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BntInativos)
                        .addGap(18, 18, 18)
                        .addComponent(BntAtivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BntBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BntAtivar)
                        .addGap(18, 18, 18)
                        .addComponent(BntDesativar)
                        .addGap(18, 18, 18)
                        .addComponent(BntAdd)
                        .addGap(18, 18, 18)
                        .addComponent(BntMenu)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenuActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntMenuActionPerformed

    private void BntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAddActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFuncao().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntAddActionPerformed

    private void BntDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntDesativarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteFuncao().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntDesativarActionPerformed

    private void BntAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAtivarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtivarFuncao().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntAtivarActionPerformed

    private void TableFuncaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableFuncaoMouseClicked
        if (evt.getClickCount() == 2) {
            int linhaSelecionada = TableFuncao.getSelectedRow();
            
            if (linhaSelecionada == -1) return;

            int id = (int) TableFuncao.getValueAt(linhaSelecionada, 0);
            Funcao funcao = funcaoController.buscarPorID(id);

            AtualizarFuncao tela = new AtualizarFuncao(funcao);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_TableFuncaoMouseClicked
    
    private FuncaoController funcaoController = new FuncaoController();
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntAdd;
    private javax.swing.JButton BntAtivar;
    private javax.swing.JButton BntAtivos;
    private javax.swing.JButton BntBuscar;
    private javax.swing.JButton BntDesativar;
    private javax.swing.JButton BntInativos;
    private javax.swing.JButton BntMenu;
    private javax.swing.JTable TableFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
